# Generated by Django 4.2.6 on 2024-02-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_websitemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemeta',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
